sudo: required
dist: trusty
bundler_args: --retry 5
os:
- osx
- linux
- windows

env:
- NODE_ENV=dev 
- NODE_ENV=prod
language: node_js
node_js:
- 8 
addons:
  # chrome: stable
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xorriso
    - desktop-file-utils

install:
- travis_retry yarn

before_script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "/Library/Application Support/VMware Tools/vmware-resolutionSet" 1920 1080;
  fi 
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start &
- sleep 5

script:
# update the xdg implementation on the machine. older version is buggy
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp node_modules/opn/xdg-open ~/bin/;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then xdg-open --version;
  fi
- yarn run build
- yarn run rebuild
- yarn run test-peruse
# - travis_retry yarn run test-exts # super occasionally times out in tests.

# separate tests for safe + auth as together throws error due to native libs
- export {no_proxy,NO_PROXY}="127.0.0.1,localhost"
- sleep 15

- yarn run package-only
# travis retry the full string to ensure repeat tests dont crash due to first try processess hanging around...
- if [[ "$NODE_ENV" != "prod" &&  "$TRAVIS_OS_NAME" != "windows" ]]; then travis_retry eval " pkill -f electron || pkill -f Peruse ||  yarn run test-exts-e2e-network";
  fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then travis_retry eval " pkill -f electron || pkill -f SAFE Browser ||  yarn run test-e2e-prod";
  fi
- if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then travis_retry eval " pkill -f electron || pkill -f SAFE Browser ||  yarn run test-exts-e2e-prod";
  fi   
- sleep 5

after_success:

- ls release
- export RELEASE="$(ls release)";
- echo "deploying ${RELEASE} to GitHub releases as tagged with ${TRAVIS_TAG}"
- cd release
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ditto -c -k --sequesterRsrc --keepParent ${RELEASE} ${RELEASE}.zip;
  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then zip -r -q ${RELEASE}.zip ${RELEASE};
  fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then 7z a ${RELEASE}.zip ${RELEASE};
  fi  
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then zip -d *.zip *.DS_Store && zip -d *.zip  __MACOSX/\*;
  fi
- cd ..
- ls release

after_failure:
- ls /home/travis/safe-browser/app/node_modules/@maidsafe/safe-node-app/src/native
# - cat ~/.local/share/applications/mimeapps.list
# - cat ~/.local/share/applications/maidsafenet-ltd-safe-browser-authenticator.desktop
- which xdg-open
- xdg-open --version
# - bash -x ~/bin/xdg-open safe-auth://whaaaaa
- cat app/log.log;
# check resolution...
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then  system_profiler SPDisplaysDataType | grep Resolution
  fi

before_deploy:
- export RELEASE_ZIP="$(ls release/*.zip)";
- echo "deploying ${RELEASE_ZIP} to GitHub releases as tagged with ${TRAVIS_TAG}"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sha256sum release/*.zip >> release/$RELEASE.txt; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shasum -a 256 release/*.zip >> release/$RELEASE.txt; fi
- if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then certutil -hashfile  release/*.zip SHA256 >> release/$RELEASE.txt; fi
- export SHA_256_SUM="$(ls release/*.txt)";


deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: koxiDMX+Hl5fNd5TliLzxKI0H0eIs0elJVs686cfFNiyqnOsBS6wimxC2YK62wk/eXaHZ7gvi1Bfy6GuRnP2fNeLTL3IZ9O9HOcUP2X/jQ12fn5wkewr6DjQx3xlN+/BGSq9IAROMq5ol0moKFBFsu4rX28ovIl2Ft6TIJio8SflM7zZFI4WJa8NNGRBkkr0Dz+MB7fuMWrI3w0paj7BeHoz5ETsmW122plpAgaMQvmpB5k+ZhpCQYE0BwEEdXPAjYLOd6MQl99b0A+bg5ZC4/aJHC6UnCMdtgnzIGSrsNOdLCR8tz6tGv4rlf2TnxH9hKTKqz1N2GmQ4MSBukQpikb6DLcQbbOhjVSPwdWWU8y/O840Y68styYdTddrXJXRnr8sBtykxje1SeB3NaTsaIlSeJu8BfTgZXjJwI46kb3kSQsKHVTDdKfn3MeXEOQpxlZ4EHYEX/ZGc3Wk/uBeGpBMqiN0svdXxZTRaxl43jiJquGsI/3Kp5Q5XPlDp/cVPpCZJjQgw8qeS3fn14axnk373IJF9biSEVdfmfml5UjGX0MwMCip0OgFWvoGlo9VqMnnLYG2ltOI85XdMnZV2DuDPSUw7ODanYhnJFTr4035+TjxpXruO7wg6cuH6YPEUJR+I7pPeSUEX40RNvYsSKW07ZTLBLCkYArTcgRSiQ8=
  file:
    - "${RELEASE_ZIP}"
    - "${SHA_256_SUM}"
  draft: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true